runtime: nodejs20
instance_class: F1

env_variables:
  API_KEY: "focuslistkey"
  INSTANCE_CONNECTION_NAME: cco-project-460113:asia-southeast2:focuslist
  DB_USER: "tahta"
  DB_PASSWORD: "tahta123"
  DB_NAME: "focuslist"

beta_settings:
  cloud_sql_instances: cco-project-460113:asia-southeast2:focuslist
