runtime: nodejs20
instance_class: F1
env_variables:
  API_KEY: "focuslistkey"
  INSTANCE_CONNECTION_NAME: "focus-vertex-457603-j1:asia-southeast2:mydatabase"
  DB_USER: "mydatabase"
  DB_PASSWORD: "radjaganteng"
  DB_NAME: "focuslist"
beta_settings:
  cloud_sql_instances: "focus-vertex-457603-j1:asia-southeast2:mydatabase"